from .autor_serializer import AutorSerializer
from .categoria_serializer import CategoriaSerializer
from .marca_serializer import MarcaSerializer
from .produto_serializer import ProdutoSerializer, ProdutoListSerializer, ProdutoDetailSerializer