# Generated by Django 4.2.5 on 2023-09-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("site", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="ace_produtos.categoria"),
                ),
                ("marca", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="ace_produtos.marca")),
            ],
        ),
    ]
