# Generated by Django 4.2.5 on 2023-10-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0003_produto_cores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="nome",
            new_name="titulo",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="autores",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="marca",
        ),
        migrations.AddField(
            model_name="produto",
            name="promocao",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Autor",
        ),
        migrations.DeleteModel(
            name="Marca",
        ),
    ]
