# Generated by Django 4.2.5 on 2023-09-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0003_alter_produto_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="ace_produtos.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="ace_produtos.marca"
            ),
        ),
    ]
