# Generated by Django 4.2.5 on 2023-09-20 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0004_alter_produto_categoria_alter_produto_marca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
    ]
