# Generated by Django 4.2.5 on 2023-10-06 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("ace_produtos", "0004_rename_nome_produto_titulo_remove_produto_autores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("promotion", models.DecimalField(decimal_places=0, max_digits=8)),
                ("description", models.TextField(blank=True, null=True)),
                ("colors", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="ace_produtos.category"
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="produtos", to="ace_produtos.gender"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
    ]
