# Generated by Django 4.2.5 on 2023-09-20 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0005_alter_produto_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="nome",
            new_name="descricao",
        ),
    ]
