# Generated by Django 4.2.5 on 2023-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("ace_produtos", "0005_category_gender_product_remove_produto_categoria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, related_name="products", to="uploader.image"),
        ),
    ]
