# Generated by Django 4.2.5 on 2023-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0006_rename_nome_categoria_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="produto",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="ace_produtos.autor"),
        ),
    ]
