# Generated by Django 4.2.5 on 2023-10-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0006_remove_product_image_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cor",
            field=models.CharField(default="#000000", max_length=100),
        ),
        migrations.AddField(
            model_name="gender",
            name="cor",
            field=models.CharField(default="#5555555", max_length=100),
        ),
    ]
