# Generated by Django 4.2.5 on 2023-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0007_autor_produto_autores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="autores",
            field=models.ManyToManyField(related_name="produtos", to="ace_produtos.autor"),
        ),
    ]
