# Generated by Django 4.2.5 on 2023-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0007_category_cor_gender_cor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cor",
            field=models.CharField(
                choices=[
                    ("bg-primary", "Azul"),
                    ("bg-cinza", "Cinza"),
                    ("bg-verde", "Verde"),
                    ("bg-vermelho", "Vermelho"),
                    ("bg-amarelo", "Amarelo"),
                    ("bg-azul-claro", "Azul Claro"),
                    ("bg-white", "Branco"),
                    ("bg-dark", "Preto"),
                ],
                default="preto",
                max_length=100,
            ),
        ),
    ]
