# Generated by Django 4.2.5 on 2023-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0008_alter_category_cor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="cor",
        ),
        migrations.RemoveField(
            model_name="gender",
            name="cor",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-primary", "Azul"),
                    ("bg-cinza", "Cinza"),
                    ("bg-verde", "Verde"),
                    ("bg-vermelho", "Vermelho"),
                    ("bg-amarelo", "Amarelo"),
                    ("bg-azul-claro", "Azul Claro"),
                    ("bg-white", "Branco"),
                    ("bg-dark", "Preto"),
                ],
                default="Preto",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="gender",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-primary", "Azul"),
                    ("bg-cinza", "Cinza"),
                    ("bg-verde", "Verde"),
                    ("bg-vermelho", "Vermelho"),
                    ("bg-amarelo", "Amarelo"),
                    ("bg-azul-claro", "Azul Claro"),
                    ("bg-white", "Branco"),
                    ("bg-dark", "Preto"),
                ],
                default="Branco",
                max_length=100,
            ),
        ),
    ]
