# Generated by Django 4.2.5 on 2023-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0009_remove_category_cor_remove_gender_cor_category_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gender",
            name="url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
