# Generated by Django 4.2.5 on 2023-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0010_category_url_gender_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-primary", "Azul"),
                    ("bg-secondary", "Cinza"),
                    ("bg-green-500", "Verde"),
                    ("bg-red-500", "Vermelho"),
                    ("bg-yellow-500", "Amarelo"),
                    ("bg-indigo-500", "Indigo"),
                    ("bg-purple-500", "Roxo"),
                    ("bg-pink-500", "Rosa"),
                ],
                max_length=100,
            ),
        ),
    ]
