# Generated by Django 4.2.5 on 2023-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0011_alter_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("t-shirt", "Camiseta"),
                    ("shirt", "Camisa"),
                    ("pants", "Calça"),
                    ("shorts", "Shorts"),
                    ("jacket", "Jaqueta"),
                    ("sweater", "Suéter"),
                    ("sweatpants", "Calça de Moletom"),
                    ("hoodie", "Moletom"),
                    ("sneaker", "Tênis"),
                ],
                default="default",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-blue-dark", "Azul Escuro"),
                    ("bg-blue-light", "Azul Claro"),
                    ("bg-secondary", "Cinza"),
                    ("bg-green", "Verde"),
                    ("bg-red", "Vermelho"),
                    ("bg-yellow-300", "Amarelo"),
                    ("bg-indigo-400", "Indigo"),
                    ("bg-purple-400", "Roxo"),
                    ("bg-pink", "Rosa"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-blue-900", "Azul Escuro"),
                    ("bg-blue-600", "Azul Claro"),
                    ("bg-green-600", "Verde"),
                    ("bg-red-600", "Vermelho"),
                    ("bg-yellow-600", "Amarelo"),
                    ("bg-indigo-600", "Indigo"),
                    ("bg-purple-600", "Roxo"),
                    ("bg-pink-600", "Rosa"),
                ],
                max_length=100,
            ),
        ),
    ]
