# Generated by Django 4.2.5 on 2023-10-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("ace_produtos", "0012_product_type_alter_category_color_alter_gender_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("url", models.CharField(default="", max_length=100)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
    ]
