# Generated by Django 4.2.5 on 2023-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0014_highlight_type_img_highlight_type_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlight",
            name="type_img",
            field=models.CharField(
                choices=[
                    ("big", "Destaque Principal - Slider"),
                    ("small", "Destaque Tamnaho Médio/Pequeno - Pagina Inicial e Menu"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="type_product",
            field=models.CharField(
                choices=[
                    ("sneaker", "Tênis"),
                    ("accessories", "Acessórios"),
                    ("shirt", "Camisa"),
                    ("pants", "Calça"),
                    ("shorts", "Shorts"),
                    ("jacket", "Jaqueta"),
                    ("sweater", "Suéter"),
                    ("sweatpants", "Calça de Moletom"),
                    ("hoodie", "Moletom"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("sneaker", "Tênis"),
                    ("accessories", "Acessórios"),
                    ("shirt", "Camisa"),
                    ("pants", "Calça"),
                    ("shorts", "Shorts"),
                    ("jacket", "Jaqueta"),
                    ("sweater", "Suéter"),
                    ("sweatpants", "Calça de Moletom"),
                    ("hoodie", "Moletom"),
                ],
                max_length=100,
            ),
        ),
    ]
