# Generated by Django 4.2.5 on 2023-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0015_alter_highlight_type_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highlight",
            name="type_img",
            field=models.CharField(
                choices=[
                    ("big", "Destaque Principal - Slider"),
                    ("small", "Destaque Médio/Pequeno - Pagina Inicial e Menu"),
                ],
                max_length=100,
            ),
        ),
    ]
