# Generated by Django 4.2.5 on 2023-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0016_alter_highlight_type_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeAccessory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("bg-blue-dark", "Azul Escuro"),
                            ("bg-blue-light", "Azul Claro"),
                            ("bg-secondary", "Cinza"),
                            ("bg-green", "Verde"),
                            ("bg-red", "Vermelho"),
                            ("bg-yellow", "Amarelo"),
                            ("bg-indigo", "Indigo"),
                            ("bg-purple", "Roxo"),
                            ("bg-pink", "Rosa"),
                            ("bg-purple-escuro", "Roxo Escuro"),
                            ("bg-indigo-blue", "Indigo Azul"),
                            ("bg-pink-dark", "Rosa Escuro"),
                            ("bg-orange", "Laranja"),
                            ("bg-orange-dark", "Laranja Escuro"),
                            ("bg-orange-light", "Laranja Claro"),
                            ("bg-green-light", "Verde Claro"),
                            ("bg-green-dark", "Verde Escuro"),
                            ("bg-green-blue", "Verde Azul"),
                        ],
                        max_length=100,
                    ),
                ),
                ("url", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-blue-dark", "Azul Escuro"),
                    ("bg-blue-light", "Azul Claro"),
                    ("bg-secondary", "Cinza"),
                    ("bg-green", "Verde"),
                    ("bg-red", "Vermelho"),
                    ("bg-yellow", "Amarelo"),
                    ("bg-indigo", "Indigo"),
                    ("bg-purple", "Roxo"),
                    ("bg-pink", "Rosa"),
                    ("bg-purple-escuro", "Roxo Escuro"),
                    ("bg-indigo-blue", "Indigo Azul"),
                    ("bg-pink-dark", "Rosa Escuro"),
                    ("bg-orange", "Laranja"),
                    ("bg-orange-dark", "Laranja Escuro"),
                    ("bg-orange-light", "Laranja Claro"),
                    ("bg-green-light", "Verde Claro"),
                    ("bg-green-dark", "Verde Escuro"),
                    ("bg-green-blue", "Verde Azul"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gender",
            name="color",
            field=models.CharField(
                choices=[
                    ("bg-blue-dark", "Azul Escuro"),
                    ("bg-blue-light", "Azul Claro"),
                    ("bg-secondary", "Cinza"),
                    ("bg-green", "Verde"),
                    ("bg-red", "Vermelho"),
                    ("bg-yellow", "Amarelo"),
                    ("bg-indigo", "Indigo"),
                    ("bg-purple", "Roxo"),
                    ("bg-pink", "Rosa"),
                    ("bg-purple-escuro", "Roxo Escuro"),
                    ("bg-indigo-blue", "Indigo Azul"),
                    ("bg-pink-dark", "Rosa Escuro"),
                    ("bg-orange", "Laranja"),
                    ("bg-orange-dark", "Laranja Escuro"),
                    ("bg-orange-light", "Laranja Claro"),
                    ("bg-green-light", "Verde Claro"),
                    ("bg-green-dark", "Verde Escuro"),
                    ("bg-green-blue", "Verde Azul"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="type_product",
            field=models.CharField(choices=[("sneaker", "Tênis"), ("accessories", "Acessórios")], max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(choices=[("sneaker", "Tênis"), ("accessories", "Acessórios")], max_length=100),
        ),
    ]
