# Generated by Django 4.2.5 on 2023-11-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0017_typeaccessory_alter_category_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type_accessory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtos",
                to="ace_produtos.typeaccessory",
            ),
            preserve_default=False,
        ),
    ]
