# Generated by Django 4.2.5 on 2023-11-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0018_product_type_accessory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type_accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtos",
                to="ace_produtos.typeaccessory",
            ),
        ),
    ]
