# Generated by Django 4.2.5 on 2023-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0019_alter_product_type_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.BooleanField(default=False),
        ),
    ]
