# Generated by Django 4.2.5 on 2023-11-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_produtos", "0021_remove_product_type_accessory_alter_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type_accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtos",
                to="ace_produtos.typeaccessory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(choices=[("sneaker", "Tênis"), ("accessories", "Acessórios")], max_length=100),
        ),
    ]
